### PR TITLE
new test, fc_openblas

### PR DESCRIPTION
**Pull request by miroi**
This new fc_openblas test is testing the known blas routine DGEMM. In the autocmake it is the math detection module, which is also checked. 

Currently, fc_openblas test is in i32lp64 mode and works on Linux machines only (waiting for ms windows openblas detection cmake macro).

### CODE REVIEW

**Comment by bast** [comment]
Thank you Miro but please submit PRs with one or very few commits.
For this please use interactive rebase or soft reset.
Each commit on `master` should in principle be cherry-pickable by others.

**Comment by miroi** [comment]
soft reset into one single commit done

**Comment by bast** [comment]
Thanks Miro but the PR contains also my changes which are already in the repo. It should only contain your changes. Can you please correct this? Please also clean up the commit message which contains many micro-commit messages and unrelated messages. Please also remove commented debug code. Thank you!

**Comment by miroi** [comment]
I did the rebase, and squeezed all commits (including yours) into one big commit. How to revert it back to the state of many small commits and do the rebase once again ?

**Comment by miroi** [comment]
closing this pr; going to reopen it elsewhere

**Comment by bast** [comment]
You need to update your branch with my changes and rebase your changes (one commit or several commits) on top of it. You can do this in this PR, no need to reopen a new one.
But please always inspect the PR before submitting it. If there is stuff in there that you did not write,
then it is not right. Sorry that I insist so much on this but this is important for other project which would immediately reject such PRs.

**Pull request closed without merging**
