### PR TITLE
test.py - wrap the expression in quotes to fix skipif error

### PR DESCRIPTION
**Pull request by miroi**
to fix https://github.com/scisoft/autocmake/issues/64#issuecomment-131316259
 wrap the expression in quotes

### CODE REVIEW

**Comment by miroi** [comment]
Bad surprise. The "@skip_on_windows" deactivates skipping the test on MS Windows, and this test crashes. Any help  how to satisfy both Linux and Windows ?

**Comment by bast** [comment]
I meant to use quotes at the place where the decorator is defined, not where it is used.
You have deactivated the decorator.

**Comment by miroi** [comment]
Where concretely should I place quotation marks to mar a string ? I have been placing them here and there, and no way - still showing this bug. I can make more tests as to the string restriction.

On top of it, couldn't this be a bug as mentioned https://bugzilla.redhat.com/show_bug.cgi?id=1109075#c1 ?

~~~
milias@lxi076.gsi.de:~/Work/qch/software/small_projects/autocmake/.py.test --version
This is py.test version 2.2.4, imported from /usr/lib/python2.7/dist-packages/pytest.pyc
milias@lxi076.gsi.de:~/Work/qch/software/small_projects/autocmake/.python -V
Python 2.7.3
~~

**Comment by miroi** [comment]
Well, the simplest solution, IMHO, is  to skip the decorator. This means all tests have to run on MS Windows as well.

**Comment by bast** [comment]
I would try to make this expression: `sys.platform == 'win32'` a string. There is no need to remove the decorator. Also please google this problem. Other people have observed this before.

**Pull request merged**
