### PR TITLE
new test fc_build_info for generating build_info.h include file

### PR DESCRIPTION
**Pull request by miroi**
- set paths to point to rado's scisoft

### CODE REVIEW

**Comment by bast** [comment]
Please let it live for a while in your project(s) before submitting it. Give it some time to mature.

Comments:
- `_static_linking` is undefined
- not all projects will use `_static_linking`
- diff points to `miroi` and to the `build_info` branch

**Comment by miroi** [comment]
Fine, there are some related comments/questions:
- *miroi* and to the *build_info* branch must be used in order to pass PR tests; only after merging the fetch url must be changed accordingly to point to scisoft/master
-  how many usefull  variables should one I collect into **build_info.h** ? I suggest at least all these which are covered by autocmake  modules to enable printing them out in software (including static_linking...)

**Comment by bast** [comment]
Then we need to fix the testing so that it does not need changing branches and repo names to pass tests. And I would start with a minimal set: compilers. Later perhaps more. Just give it some time. It is better if you debug all "child diseases" of the module over the next days and weeks before we make it a standard module.

**Comment by miroi** [comment]
1. Ad testing: if someone asks for PR of his new test which is downloading(fetching) files from brand new subdirectories, nonexisting in scisoft/master - there is no other way than pointing to user's fork/branch first, and after merge change it to main repo/master. Or is there another solution without  changing repo/branches names ?

2. Ad suitable set of variables into **git_info.h**:  Within the autocmake development module, we can not test them all. One-two variables can be active in the restricted test (like fortran compiler, operating system, cmake version etc), remaining will anyhow be set to "unknown". They can be tested only in  external projects (mathlibs-tester), where the developer can freely "pack" all modules into autocmake.cfg

**Comment by bast** [comment]
1) Then we need to adapt the testing so that it does not download anything. Then this problem disappears.
2) I agree. They need to be tested in external projects. And it will take some time for the code to mature. It is better if you do the fixes on your fork rather than submitting a PR for each fix. So letting the code mature on the fork is not only good for me but also better for you.

**Pull request closed without merging**
