### PR TITLE
simple fortran test for checking the generated "git_info.h"

### PR DESCRIPTION
**Pull request by miroi**
We need to test also the "modules/git_info/git_info.cmake".

### CODE REVIEW

**Comment by bast** [comment]
Few comments:
- The relative `#include` looks strange. Better use `include_directories()` in `CMakeLists.txt`.
- A `Test OK` string or similar would be better than `Hello World!`.
- It is not necessary to check on `GIT_INFO_H_INCLUDED`. This is always set if `git_info.h` is included. It is there to prevent the file to be included multiple times. This is not to be used in the Fortran code.
- Implicit save (`logical :: test_ok=.false.`) is a dangerous programming practice. Better define and set on different lines. It does not matter here but I would avoid it by principle.
- Please prefer the modern and intuitive ">" over the old-school and cryptic ".gt.".
- Please use spaces around operators (such as ".and." or ".gt." in this example).

**Comment by miroi** [comment]
I updated/rebased this branch according to the master. Hopefully both tests will pass.

**Comment by miroi** [comment]
Tests are green, boss :), hehe.

**Comment by bast** [comment]
Thanks!

**Pull request merged**
