### PR TITLE
added (setup.py) flag for CMake build system generators into autocmake.cfg

### PR DESCRIPTION
**Pull request by miroi**
I am adding this example to the two autocmake.cfg files of the autocmake testing suite.

Fortunately, there was no need to modify any python/cmake script. Later, when I get renewed connection to the Windows server, I shall add some documentation. The corresponding issue #12 can remain open.

### CODE REVIEW

**Comment by bast** [comment]
Thank you. It is indeed possible to introduce such changes via `autocmake.cfg`. But - well - for once this change breaks the Travis tests. Also I would prefer to have the change in the "core" `update.py` because it would be less intrusive to the tests and would also require less boilerplate. I think this is a flag that cnan be generally interesting and should be generally available to all projects. Also if you submit a PR, please submit them in nice "cherry-pickable" units (no pull-merge commits, no unrelated commits). For this you may need to rebase and squash the changes. We aim at having a "nice" history.

**Comment by miroi** [comment]
Hi,

so in order to repeat this pull commit, do I have first to close this request, than do  changes on my fork / in my git history and, finally ask for a new (more complete) pull request ?

**Comment by bast** [comment]
No you don't need to close this one. You can keep it open - it will refresh and automatically rerun
tests once you push to it.

**Comment by miroi** [comment]
Ah, I see that this open pull request is watching commits in my fork. And is Travis-CI checking my fork using original travis-ci prescription in radovan't source ?

**Comment by bast** [comment]
Travis will test your commits because you filed a PR. It will stop if you close it.
Anyway now you can basically close it because it contains several
unrelated things.

**Comment by bast** [comment]
I will now close this PR. You can test the changes also locally.

**Pull request closed without merging**
