### PR TITLE
added new test, combining lapack and blas routines

### PR DESCRIPTION
**Pull request by miroi**
New test, named as fc_lapack. Tests dgesv-dgemv-dnrm2 routines of lapack and blas.

### CODE REVIEW

**Comment by miroi** [comment]
Well, probably I should do the rebase, so that there is only one commit, right ?

**Comment by miroi** [comment]
How simple test turned into nightmare...The rand() is causing problems (with MKL), trying to fix it.

**Comment by bast** [comment]
I am closing this PR for the moment.
Few advices:
- Don't submit PR which break tests (unless they reveal bugs in previous testing).
- Don't submit several things in one PR (here for instance I am not sure that the -rdynamic stuff has to be here; the CMake modules have to work everywhere but the tests don't have to; I don't mind so much if the tests fail with PGI if I know that math works with PGI; in any case the -rdynamic is a separate issue). If you solve several issues with one PR you risk that the PR cannot be accepted because feature 1 needs more review although feature 2 is perhaps fine.
- Don't submit patches over several commits. Commits have to be cherry-pickable.
- Don't submit PR immediately. Let the code ripe on your fork for few days and see how it behaves. Sleep over it. Submit it later.

**Comment by miroi** [comment]
Hi,

I am trying to fix this test to work for Intel,Portlan, GNU...due to the rand() function. Then I would rebase it again. Or should I split this PR into several pull requests ?

**Comment by bast** [comment]
If rand() is a problem why use it? I would design a test that does not need random numbers.

**Comment by miroi** [comment]
This test is more complex - it's using lapack and blas routines. On top of, it uses the rand() function to generate random data (fill matrix A,vector b for solving linear equations), and this requires extra treatment for GNU, Intel, PGI.

**Comment by bast** [comment]
But why not make it not complex? We don't want to test LAPACK we just want to test that we are able to detect and properly link LAPACK. This can be tested with a very simple test.

**Comment by miroi** [comment]
IMO, in the package, we would need not only test lapack detection and linking, but also the correctness of one important lapack routine DGESV (as is done in fc_blas test for blas routine).

For testing roots of linear equations (DGESV) I am using blas routines dgemv, dnrm2 (norm of zero vector of Ax-b=0). And rand() is used for filling arrays with random numbers.

**Comment by miroi** [comment]
Well, concerning autocmake fc_XXX tests: the user who downloads the autocmake should be able to run them also with non-GNU compilers/libraries (let say, in the combination of PG Fortran + MKL + i8). Travis-CI shows only for gnu packages, we need to test more compilers/libraries.

**Comment by miroi** [comment]
I need to make DIRAC-autocmake running for "PGI + MKL + i8", and this proposed test is good prelude for that, IMO.

**Comment by bast** [comment]
Currently we define that Autocmake tests need to pass on GNU. We cannot require more because we have no way of automatically test proprietary compilers on Travis anyway. Of course the modules need to work "everywhere". If this is not the case and there is a problem in the module, then we will know that via issuess. Note that the `-rdynamic` problem is not a problem of the `math_libs.cmake` module.
As to the LAPACK test of course you want to make sure that the test verifies that the numbers are correct but this can be done with a very simple test. Random numbers are not necessary if problematic.
Simple is better than complex. Complex is better than complicated.

**Pull request closed without merging**
