### PR TITLE
fix for Python of version lower than 2.7

### PR DESCRIPTION
**Pull request by miroi**
According to https://github.com/scisoft/autocmake/issues/64#issuecomment-129143029 .

### CODE REVIEW

**Comment by bast** [comment]
Hi Miro please just change the commit message and the comments. This has in my understanding
nothing to do with Python 2.7 or lower but with the fact that your compilation
writes warnings to stderr.

**Comment by bast** [comment]
Also if you fix an issue with a PR, please auto-close it with the commit message.

**Comment by miroi** [comment]
Good, after some playing with commit message and rebasing I imbue the change. Is it OK now ?

**Comment by bast** [comment]
Do you need also the second assert removed? Compilation should write only to the first.

**Comment by miroi** [comment]
I fixed it, but where is "All checks have passed" ?

**Comment by miroi** [comment]
Ah, I see, it showed up after some while.

**Pull request merged**
