### PR TITLE
new test: cc_lapack

### PR DESCRIPTION
**Pull request by miroi**
- extended math_libs.cmake for C headers detection
- static_linking tests included
- rearranged math-libs order for better libraries detection
- no int64 for cc_lapack
- added include/ directory to %path% to detect clapack.h in appveyor

### CODE REVIEW

**Comment by miroi** [comment]
Getting errmsg = 'Too Many Requests', ERROR: could not fetch //github.com/docopt/docopt/raw/master/docopt.py - some connectivity error. I don't see button to repeat the travis-ci test ... any help ?

**Comment by bast** [comment]
Some remarks:
- what is the `dpkg -S clapack.h` for? and why not add a comment?
- why is `roots_ok` an unsigned char?
- please use an indentation of four spaces which is basically standard
- please use consistent spacing in the sources
- please do not put several expressions on one line

**Comment by miroi** [comment]
fixes and  rebase done, is it already OK ?

**Comment by bast** [comment]
It looks like the change in `.travis.yml` is redundant. Please try to keep the changeset to the minimum.

**Comment by miroi** [comment]
fixed and rebased; both tests are OK

**Comment by bast** [comment]
:thumbsup:

**Pull request merged**
